```{r}
x<-c(1,2,3,4)
class(x)
```
```{r}
gender<-c("male","female")
gender
class(gender)
2:7
class(2:7)
seq(from=1, to = 7, by=1/3)
class(seq(from=1, to = 7, by=1/3))
```
```{r}
rep(1,times=10)
class(rep(1,times=10))

```

```{r}
rep(1:3,times=5)
rep("martin",times=5)
rep(seq(from=2,to=5,by=0.5),times=5)
```

```{r}
rep(c("a","b"),times=5)


```

```{r}
x<-1:5
x
y<-c(1,3,5,7,9)
y
x+5
x-5
x*10
x/10
x
#if two vectors are of the same length, we may add/subtract/mul/div corresponding elements

```

```{r}
x<-1:5
y<-c(1,3,5,7,9)
class(x)
class(y)
#There are multiple classes that are grouped together as "numeric" classes, the 2 most common of which are double (for double precision floating point numbers) and integer. R will automatically convert between the numeric classes when needed, so for the most part it does not matter to the casual user whether the number 3 is currently stored as an integer or as a double. Most math is done using double precision, so that is often the default storage.



```

```{r}
x*y
x+y
x-y
x[3]
y[-3]
# y[-3] will print y except third element ie 5
y[1:3]

```
```{r}
y[c(1,5)]#just 1 st and 5th element of y
y[-c(1,5)]#except 1st and 5 th element of y
y[y<6]
mat<- matrix(c(1:9),nrow=3,byrow = T)
mat
```

```{r}

mat<- matrix(c(1:9),nrow=3,byrow = FALSE)
mat

mat2<- matrix(c(1:9),nrow=3,byrow = F)
mat2


mat3<- matrix(c(1,2,3,4,5,6,7,8,9),nrow=3,byrow = T)
mat3
```

```{r}
mat3[1,2]
mat3[c(1,3),2]   #row 1 and 3 and column 2
class(c(1,2))
```

```{r}
mat3[2,]   # row 2 all columns
mat3*10
```

```{r}

```

```{r}

```

```{r}

```

